import postgres from 'postgres';
import { BOT_PRESETS } from '@longrak/shared/presets';
import { toSheet } from '@longrak/shared/catalog';
import { DEFAULT_PLANS } from '@longrak/shared/plans';

/**
 * PostgreSQL holds accounts, sessions, every private chat, the public character catalog and billing.
 * DATABASE_URL points at it; the schema is created and upgraded on first use (see MIGRATIONS).
 */

export type Sql = postgres.Sql<{ bigint: number }>;
/** A schema change: SQL, or a step that needs code (e.g. to insert bundled data). Runs once, in order. */
type Migration = string | ((tx: postgres.TransactionSql<{ bigint: number }>) => Promise<void>);

/**
 * Applied in order, once each; the index is the version. Never edit a shipped entry, append a new one.
 * Times are milliseconds since epoch (bigint, read back as numbers) to match the app's Date.now().
 */
const MIGRATIONS: Migration[] = [
  `
  CREATE EXTENSION IF NOT EXISTS citext;

  CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username citext NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at bigint NOT NULL,
    is_admin boolean NOT NULL DEFAULT false,
    email citext UNIQUE,
    phone text,
    consent_version integer NOT NULL DEFAULT 0,
    consent_at bigint,
    marketing_consent boolean NOT NULL DEFAULT false,
    stripe_customer_id text
  );

  CREATE TABLE sessions (
    token_hash text PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at bigint NOT NULL
  );
  CREATE INDEX sessions_user ON sessions (user_id);

  -- Each account's own chats. Private: no admin endpoint reads this table.
  CREATE TABLE characters (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    id text NOT NULL,
    data jsonb NOT NULL,
    updated_at bigint NOT NULL,
    PRIMARY KEY (user_id, id)
  );

  -- Admin-editable overrides (AI model, Workers AI credentials). Empty or missing falls back to env.
  CREATE TABLE settings (
    key text PRIMARY KEY,
    value text NOT NULL
  );

  -- Public characters anyone can start a chat with. Holds the character sheet only, never a conversation.
  CREATE TABLE catalog (
    id text PRIMARY KEY,
    author_id integer REFERENCES users(id) ON DELETE SET NULL,
    -- The author's private character this was submitted from, so resubmitting updates the same entry.
    source_id text,
    data jsonb NOT NULL,
    status text NOT NULL DEFAULT 'draft',   -- draft | pending | published | rejected
    tier integer NOT NULL DEFAULT 0,        -- lowest plan level that may chat with it
    review_note text NOT NULL DEFAULT '',
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    published_at bigint
  );
  CREATE UNIQUE INDEX catalog_source ON catalog (author_id, source_id) WHERE source_id IS NOT NULL;

  CREATE TABLE plans (
    id text PRIMARY KEY,
    name text NOT NULL,
    level integer NOT NULL,
    price integer NOT NULL,                 -- satang per period; 0 for the free plan
    interval text NOT NULL,                 -- month | year
    active boolean NOT NULL DEFAULT true,
    features jsonb NOT NULL,                -- see lib/plans.ts
    perks jsonb NOT NULL DEFAULT '[]'       -- selling points shown on the membership page
  );

  -- At most one membership per account; no row (or an expired one) means the free plan.
  CREATE TABLE subscriptions (
    user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    plan_id text NOT NULL REFERENCES plans(id),
    source text NOT NULL,                   -- stripe | code | admin
    status text NOT NULL,                   -- active | trialing | past_due | canceled | incomplete ...
    current_period_end bigint NOT NULL,
    cancel_at_period_end boolean NOT NULL DEFAULT false,
    stripe_subscription_id text,
    updated_at bigint NOT NULL
  );

  CREATE TABLE coupons (
    code citext PRIMARY KEY,
    kind text NOT NULL,                     -- percent | amount | free_days
    value integer NOT NULL,                 -- percent, satang, or days
    duration text NOT NULL DEFAULT 'once',  -- once | forever (discounts only)
    plan_ids jsonb,                         -- list; NULL = every paid plan
    max_redemptions integer,                -- people who may use it; NULL = unlimited
    expires_at bigint,
    active boolean NOT NULL DEFAULT true,
    note text NOT NULL DEFAULT '',
    stripe_coupon_id text,
    created_at bigint NOT NULL
  );

  CREATE TABLE coupon_redemptions (
    code citext NOT NULL REFERENCES coupons(code) ON DELETE CASCADE ON UPDATE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    at bigint NOT NULL,
    PRIMARY KEY (code, user_id)
  );

  -- AI calls per account per day (Asia/Bangkok), for the plan's daily limit.
  CREATE TABLE usage (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    day text NOT NULL,
    chat integer NOT NULL DEFAULT 0,
    other integer NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, day)
  );

  -- Stripe retries webhooks; remember which events were already applied.
  CREATE TABLE stripe_events (
    id text PRIMARY KEY,
    at bigint NOT NULL
  );
  `,
  `
  -- Problems and suggestions people send from the app. Never includes their chats.
  CREATE TABLE bug_reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    kind text NOT NULL,                     -- bug | idea | other
    title text NOT NULL,
    body text NOT NULL,
    screenshot text,                        -- data:image/jpeg URL, if attached
    context jsonb,                          -- page, browser, screen size: only when the person ticked it
    status text NOT NULL DEFAULT 'open',    -- open | in_progress | resolved | closed
    admin_reply text NOT NULL DEFAULT '',
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL
  );
  CREATE INDEX bug_reports_status ON bug_reports (status, created_at DESC);
  CREATE INDEX bug_reports_user ON bug_reports (user_id, created_at DESC);
  `,
  `
  -- Real date of birth (YYYY-MM-DD), which decides 18+ mode on the server. Players under 20 also need
  -- a guardian's consent under the PDPA.
  ALTER TABLE users ADD COLUMN birthdate text CHECK (birthdate ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$');
  ALTER TABLE users ADD COLUMN guardian_consent boolean NOT NULL DEFAULT false;

  -- Sign-in, sign-up and report throttles, shared by every app instance and kept across restarts.
  CREATE TABLE rate_limits (
    key text PRIMARY KEY,
    count integer NOT NULL,
    lim integer NOT NULL,
    until bigint NOT NULL
  );
  CREATE INDEX rate_limits_until ON rate_limits (until);
  `,
  `
  -- Plus and Pro move from yearly ฿799/฿999 to monthly ฿99/฿199. Only rows still at the old defaults,
  -- so a price an admin already set is kept. Existing subscribers keep what they signed up for.
  UPDATE plans SET price = 9900, interval = 'month' WHERE id = 'plus' AND price = 79900 AND interval = 'year';
  UPDATE plans SET price = 19900, interval = 'month' WHERE id = 'pro' AND price = 99900 AND interval = 'year';
  `,
  // The ready-made characters join the catalog, each with a face. The seeded Iris becomes Hayun unless an
  // admin has changed her; any id already taken is left alone. Spaced timestamps keep the list's order.
  async (tx) => {
    const now = Date.now();
    for (const [i, { id, imagePrompt: _p, ...preset }] of BOT_PRESETS.entries()) {
      const sheet = toSheet({ ...preset, adult: false });
      const at = now - i * 1000;
      if (id === 'char-1') {
        await tx`
          UPDATE catalog SET data = ${tx.json(sheet)}, updated_at = ${at}, published_at = ${at}
          WHERE id = 'char-1' AND data->>'name' = 'ไอริส (Iris)'`;
      }
      await tx`
        INSERT INTO catalog (id, data, status, created_at, updated_at, published_at)
        VALUES (${id}, ${tx.json(sheet)}, 'published', ${at}, ${at}, ${at})
        ON CONFLICT (id) DO NOTHING`;
    }
  },
  `
  -- Tokens pay for replies past the free messages and unlock unlimited chat with one character.
  ALTER TABLE users ADD COLUMN tokens integer NOT NULL DEFAULT 0 CHECK (tokens >= 0);

  -- Every change to a balance, for support and refunds.
  CREATE TABLE token_ledger (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    delta integer NOT NULL,
    reason text NOT NULL,                   -- purchase | checkin | message | refund | unlock | admin
    ref text,                               -- Stripe checkout session, character key or admin note
    at bigint NOT NULL
  );
  CREATE INDEX token_ledger_user ON token_ledger (user_id, at DESC);
  -- Stripe may report one payment more than once; it is credited once.
  CREATE UNIQUE INDEX token_ledger_purchase ON token_ledger (ref) WHERE reason = 'purchase';

  -- Replies per account per character, ever. The key is cat:<catalog id> for a catalog character
  -- (so restarting the chat doesn't reset it) or own:<character id>.
  CREATE TABLE character_usage (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    char_key text NOT NULL,
    free_used integer NOT NULL DEFAULT 0,
    paid integer NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, char_key)
  );

  CREATE TABLE character_unlocks (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    char_key text NOT NULL,
    tokens integer NOT NULL,
    at bigint NOT NULL,
    PRIMARY KEY (user_id, char_key)
  );

  -- One check-in per account per day (Asia/Bangkok).
  CREATE TABLE checkins (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    day text NOT NULL,
    tokens integer NOT NULL,
    PRIMARY KEY (user_id, day)
  );

  ALTER TABLE catalog ADD COLUMN unlock_price integer CHECK (unlock_price >= 0);   -- NULL = the default price
  `,
  // Free gets 15 free replies a day; members lose the daily cap and check in for tokens. Every plan gets
  // 20 free replies per character. Limits and perks an admin already changed are kept.
  async (tx) => {
    const perkSwap: Record<string, string[]> = {
      'ข้อความต่อวันเยอะกว่า Free มาก': ['คุยได้ไม่จำกัดจำนวนต่อวัน', 'เช็คอินรับ 100 โทเคนทุกวัน ไว้ปลดล็อกตัวละครที่ชอบ'],
      'คุยได้แทบไม่จำกัด': ['คุยได้ไม่จำกัดจำนวนต่อวัน', 'เช็คอินรับ 100 โทเคนทุกวัน ไว้ปลดล็อกตัวละครที่ชอบ'],
    };
    const rows = await tx<{ id: string; features: Record<string, number | string>; perks: string[] }[]>`SELECT id, features, perks FROM plans`;
    for (const r of rows) {
      const free = r.id === 'free';
      const daily = r.features.dailyMessages;
      const features = {
        ...r.features,
        dailyMessages: free ? (daily === 30 ? 15 : daily) : daily === 300 ? 0 : daily,
        freePerCharacter: 20,
        checkinTokens: free ? 0 : 100,
      };
      const perks = r.perks.flatMap((p) => perkSwap[p] ?? [p]);
      await tx`UPDATE plans SET features = ${tx.json(features)}, perks = ${tx.json(perks)} WHERE id = ${r.id}`;
    }
  },
  `
  -- One-off PromptPay QR payments (Stripe PaymentIntents). Each paid one adds a plan period with
  -- subscriptions.source = 'promptpay'; PromptPay can't be charged again automatically.
  CREATE TABLE promptpay_payments (
    id text PRIMARY KEY,                    -- Stripe PaymentIntent id
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id text NOT NULL REFERENCES plans(id),
    code citext,                            -- discount code used, counted once paid
    amount integer NOT NULL,                -- satang
    status text NOT NULL,                   -- pending | paid | canceled
    qr text NOT NULL,                       -- Stripe-hosted QR image (SVG)
    test_url text,                          -- test mode only: Stripe's page to simulate paying
    created_at bigint NOT NULL,
    paid_at bigint
  );
  CREATE INDEX promptpay_payments_user ON promptpay_payments (user_id, created_at DESC);
  `,
  // Members chat without a per-character cap ("คุยได้ไม่จำกัด"); only Free keeps its 20. A cap an admin set
  // to something other than 20 is kept.
  async (tx) => {
    const rows = await tx<{ id: string; features: Record<string, number | string> }[]>`SELECT id, features FROM plans WHERE id <> 'free'`;
    for (const r of rows) {
      if (r.features.freePerCharacter !== 20) continue;
      await tx`UPDATE plans SET features = ${tx.json({ ...r.features, freePerCharacter: 0 })} WHERE id = ${r.id}`;
    }
  },
  `
  -- For the admin's user list. last_seen_at moves at most once a minute (lib/auth.ts currentUser);
  -- before this, the newest chat update is the best guess.
  ALTER TABLE users ADD COLUMN last_login_at bigint;
  ALTER TABLE users ADD COLUMN last_seen_at bigint;
  UPDATE users u SET last_seen_at = (SELECT max(c.updated_at) FROM characters c WHERE c.user_id = u.id);
  `,
  `
  -- An admin's frozen copy of a chat, kept as evidence for a report or dispute. Outlives the chat and
  -- the account (user_id goes NULL, username stays) until expires_at, then it is deleted
  -- (lib/evidence.ts). Never updated: there is no endpoint that changes one.
  CREATE TABLE chat_evidence (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    username text NOT NULL,
    chat_id text NOT NULL,
    chat jsonb NOT NULL,
    note text NOT NULL DEFAULT '',
    saved_by text NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL
  );
  CREATE INDEX chat_evidence_expires ON chat_evidence (expires_at);
  `,
  `
  -- Money actually received, for the admin's revenue figures: card invoices, token packs and PromptPay.
  -- Refunds are negative rows. Stripe's own records stay the source of truth for accounting.
  CREATE TABLE payments (
    id text PRIMARY KEY,                    -- Stripe invoice, checkout session, PaymentIntent or refund id
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    kind text NOT NULL,                     -- subscription | tokens | promptpay | refund
    plan_id text,
    amount integer NOT NULL,                -- satang; negative for a refund
    at bigint NOT NULL
  );
  CREATE INDEX payments_at ON payments (at);
  INSERT INTO payments (id, user_id, kind, plan_id, amount, at)
    SELECT id, user_id, 'promptpay', plan_id, amount, coalesce(paid_at, created_at) FROM promptpay_payments WHERE status = 'paid';
  `,
  // Character pictures drawn with AI, counted per day like chat.
  `ALTER TABLE usage ADD COLUMN image integer NOT NULL DEFAULT 0;`,
  // Pictures per day and their quality go up with the plan. A plan an admin already gave these keeps them.
  async (tx) => {
    const defaults: Record<number, { dailyImages: number; imageQuality: string }> = {
      0: { dailyImages: 3, imageQuality: 'standard' },
      1: { dailyImages: 20, imageQuality: 'hd' },
      2: { dailyImages: 60, imageQuality: 'premium' },
    };
    const rows = await tx<{ id: string; level: number; features: Record<string, number | string> }[]>`SELECT id, level, features FROM plans`;
    for (const r of rows) {
      const d = defaults[Math.min(Math.max(r.level, 0), 2)];
      const features = { ...d, ...r.features };
      await tx`UPDATE plans SET features = ${tx.json(features)} WHERE id = ${r.id}`;
    }
  },
];

async function migrate(sql: Sql) {
  await sql`CREATE TABLE IF NOT EXISTS schema_migrations (version integer PRIMARY KEY, applied_at bigint NOT NULL)`;
  // One instance migrates at a time; the others wait on the lock and then find nothing left to do.
  await sql.begin(async (tx) => {
    await tx`SELECT pg_advisory_xact_lock(72106)`;
    const done = new Set((await tx<{ version: number }[]>`SELECT version FROM schema_migrations`).map((r) => r.version));
    for (const [version, script] of MIGRATIONS.entries()) {
      if (done.has(version)) continue;
      if (typeof script === 'string') await tx.unsafe(script);
      else await script(tx);
      await tx`INSERT INTO schema_migrations ${tx({ version, applied_at: Date.now() })}`;
    }

    for (const p of DEFAULT_PLANS) {
      await tx`
        INSERT INTO plans (id, name, level, price, interval, features, perks)
        VALUES (${p.id}, ${p.name}, ${p.level}, ${p.price}, ${p.interval}, ${tx.json(p.features)}, ${tx.json(p.perks)})
        ON CONFLICT (id) DO NOTHING`;
    }
  });
}

// Survives Next's dev hot reloads, so edits don't open a new pool each time.
const g = globalThis as unknown as { __pg?: Promise<Sql> };

/** The connection pool, with the schema up to date. */
export function db(): Promise<Sql> {
  if (!g.__pg) {
    const url = process.env.DATABASE_URL;
    if (!url) throw new Error('DATABASE_URL is not set');
    const sql = postgres(url, {
      max: Number(process.env.DATABASE_POOL_SIZE) || 10,
      // count(*) and the bigint timestamps come back as numbers; ms since epoch fits safely.
      types: { bigint: { to: 20, from: [20], serialize: (x: number) => String(x), parse: (x: string) => Number(x) } },
      onnotice: () => {},
    }) as unknown as Sql;
    g.__pg = migrate(sql).then(
      () => sql,
      (err) => {
        g.__pg = undefined;
        throw err;
      },
    );
  }
  return g.__pg;
}
