import postgres from 'postgres';
import { DEFAULT_CHARACTERS } from '@longrak/shared/presets';
import { DEFAULT_PLANS } from '@longrak/shared/plans';

/**
 * PostgreSQL holds accounts, sessions, every private chat, the public character catalog and billing.
 * DATABASE_URL points at it; the schema is created and upgraded on first use (see MIGRATIONS).
 */

export type Sql = postgres.Sql<{ bigint: number }>;

/**
 * Applied in order, once each; the index is the version. Never edit a shipped entry, append a new one.
 * Times are milliseconds since epoch (bigint, read back as numbers) to match the app's Date.now().
 */
const MIGRATIONS: string[] = [
  `
  CREATE EXTENSION IF NOT EXISTS citext;

  CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username citext NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at bigint NOT NULL,
    is_admin boolean NOT NULL DEFAULT false,
    email citext UNIQUE,
    phone text,
    consent_version integer NOT NULL DEFAULT 0,
    consent_at bigint,
    marketing_consent boolean NOT NULL DEFAULT false,
    stripe_customer_id text
  );

  CREATE TABLE sessions (
    token_hash text PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at bigint NOT NULL
  );
  CREATE INDEX sessions_user ON sessions (user_id);

  -- Each account's own chats. Private: no admin endpoint reads this table.
  CREATE TABLE characters (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    id text NOT NULL,
    data jsonb NOT NULL,
    updated_at bigint NOT NULL,
    PRIMARY KEY (user_id, id)
  );

  -- Admin-editable overrides (AI model, Workers AI credentials). Empty or missing falls back to env.
  CREATE TABLE settings (
    key text PRIMARY KEY,
    value text NOT NULL
  );

  -- Public characters anyone can start a chat with. Holds the character sheet only, never a conversation.
  CREATE TABLE catalog (
    id text PRIMARY KEY,
    author_id integer REFERENCES users(id) ON DELETE SET NULL,
    -- The author's private character this was submitted from, so resubmitting updates the same entry.
    source_id text,
    data jsonb NOT NULL,
    status text NOT NULL DEFAULT 'draft',   -- draft | pending | published | rejected
    tier integer NOT NULL DEFAULT 0,        -- lowest plan level that may chat with it
    review_note text NOT NULL DEFAULT '',
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    published_at bigint
  );
  CREATE UNIQUE INDEX catalog_source ON catalog (author_id, source_id) WHERE source_id IS NOT NULL;

  CREATE TABLE plans (
    id text PRIMARY KEY,
    name text NOT NULL,
    level integer NOT NULL,
    price integer NOT NULL,                 -- satang per period; 0 for the free plan
    interval text NOT NULL,                 -- month | year
    active boolean NOT NULL DEFAULT true,
    features jsonb NOT NULL,                -- see lib/plans.ts
    perks jsonb NOT NULL DEFAULT '[]'       -- selling points shown on the membership page
  );

  -- At most one membership per account; no row (or an expired one) means the free plan.
  CREATE TABLE subscriptions (
    user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    plan_id text NOT NULL REFERENCES plans(id),
    source text NOT NULL,                   -- stripe | code | admin
    status text NOT NULL,                   -- active | trialing | past_due | canceled | incomplete ...
    current_period_end bigint NOT NULL,
    cancel_at_period_end boolean NOT NULL DEFAULT false,
    stripe_subscription_id text,
    updated_at bigint NOT NULL
  );

  CREATE TABLE coupons (
    code citext PRIMARY KEY,
    kind text NOT NULL,                     -- percent | amount | free_days
    value integer NOT NULL,                 -- percent, satang, or days
    duration text NOT NULL DEFAULT 'once',  -- once | forever (discounts only)
    plan_ids jsonb,                         -- list; NULL = every paid plan
    max_redemptions integer,                -- people who may use it; NULL = unlimited
    expires_at bigint,
    active boolean NOT NULL DEFAULT true,
    note text NOT NULL DEFAULT '',
    stripe_coupon_id text,
    created_at bigint NOT NULL
  );

  CREATE TABLE coupon_redemptions (
    code citext NOT NULL REFERENCES coupons(code) ON DELETE CASCADE ON UPDATE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    at bigint NOT NULL,
    PRIMARY KEY (code, user_id)
  );

  -- AI calls per account per day (Asia/Bangkok), for the plan's daily limit.
  CREATE TABLE usage (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    day text NOT NULL,
    chat integer NOT NULL DEFAULT 0,
    other integer NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, day)
  );

  -- Stripe retries webhooks; remember which events were already applied.
  CREATE TABLE stripe_events (
    id text PRIMARY KEY,
    at bigint NOT NULL
  );
  `,
  `
  -- Problems and suggestions people send from the app. Never includes their chats.
  CREATE TABLE bug_reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    kind text NOT NULL,                     -- bug | idea | other
    title text NOT NULL,
    body text NOT NULL,
    screenshot text,                        -- data:image/jpeg URL, if attached
    context jsonb,                          -- page, browser, screen size: only when the person ticked it
    status text NOT NULL DEFAULT 'open',    -- open | in_progress | resolved | closed
    admin_reply text NOT NULL DEFAULT '',
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL
  );
  CREATE INDEX bug_reports_status ON bug_reports (status, created_at DESC);
  CREATE INDEX bug_reports_user ON bug_reports (user_id, created_at DESC);
  `,
  `
  -- Real date of birth (YYYY-MM-DD), which decides 18+ mode on the server. Players under 20 also need
  -- a guardian's consent under the PDPA.
  ALTER TABLE users ADD COLUMN birthdate text CHECK (birthdate ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$');
  ALTER TABLE users ADD COLUMN guardian_consent boolean NOT NULL DEFAULT false;

  -- Sign-in, sign-up and report throttles, shared by every app instance and kept across restarts.
  CREATE TABLE rate_limits (
    key text PRIMARY KEY,
    count integer NOT NULL,
    lim integer NOT NULL,
    until bigint NOT NULL
  );
  CREATE INDEX rate_limits_until ON rate_limits (until);
  `,
];

async function migrate(sql: Sql) {
  await sql`CREATE TABLE IF NOT EXISTS schema_migrations (version integer PRIMARY KEY, applied_at bigint NOT NULL)`;
  // One instance migrates at a time; the others wait on the lock and then find nothing left to do.
  await sql.begin(async (tx) => {
    await tx`SELECT pg_advisory_xact_lock(72106)`;
    const done = new Set((await tx<{ version: number }[]>`SELECT version FROM schema_migrations`).map((r) => r.version));
    for (const [version, script] of MIGRATIONS.entries()) {
      if (done.has(version)) continue;
      await tx.unsafe(script);
      await tx`INSERT INTO schema_migrations ${tx({ version, applied_at: Date.now() })}`;
    }

    for (const p of DEFAULT_PLANS) {
      await tx`
        INSERT INTO plans (id, name, level, price, interval, features, perks)
        VALUES (${p.id}, ${p.name}, ${p.level}, ${p.price}, ${p.interval}, ${tx.json(p.features)}, ${tx.json(p.perks)})
        ON CONFLICT (id) DO NOTHING`;
    }

    // A fresh install starts with the bundled sample character in the catalog.
    const [{ n }] = await tx<{ n: number }[]>`SELECT count(*) AS n FROM catalog`;
    if (!n) {
      const now = Date.now();
      for (const c of DEFAULT_CHARACTERS) {
        const { messages: _m, notes: _n, notedUpTo: _u, updatedAt: _t, userName: _p, ...sheet } = c;
        await tx`
          INSERT INTO catalog (id, data, status, created_at, updated_at, published_at)
          VALUES (${c.id}, ${tx.json(sheet)}, 'published', ${now}, ${now}, ${now})`;
      }
    }
  });
}

// Survives Next's dev hot reloads, so edits don't open a new pool each time.
const g = globalThis as unknown as { __pg?: Promise<Sql> };

/** The connection pool, with the schema up to date. */
export function db(): Promise<Sql> {
  if (!g.__pg) {
    const url = process.env.DATABASE_URL;
    if (!url) throw new Error('DATABASE_URL is not set');
    const sql = postgres(url, {
      max: Number(process.env.DATABASE_POOL_SIZE) || 10,
      // count(*) and the bigint timestamps come back as numbers; ms since epoch fits safely.
      types: { bigint: { to: 20, from: [20], serialize: (x: number) => String(x), parse: (x: string) => Number(x) } },
      onnotice: () => {},
    }) as unknown as Sql;
    g.__pg = migrate(sql).then(
      () => sql,
      (err) => {
        g.__pg = undefined;
        throw err;
      },
    );
  }
  return g.__pg;
}
